name: Test

on: 
 push:
  branch:
    - 'develop'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      - name: Test this action
        uses: Serhioromano/github-action-test@develop
        with:
          input1: yes
          input2: String here
      - name: See file CLI
        run: |
          pwd
          cat test.txt
          ls -la